### ISSUE TITLE
Status bar label is blank if no options are selected

### ISSUE THREAD

**Issue by riuson** [robole/vscode-marky-stats#8]
Hello,
You have removed the method that was meant to prevent the panel from disappearing from the status bar by unchecking all the checkboxes.
After that, the panel can be restored through Ctrl+Shift+P or by manually editing the settings file. Since the click on the panel in the status bar is no longer available.
This is very counterintuitive.
If user want hide items from statusbar, he can just disable extension.
```
-  controlEmptiness(items) {
-    if (items.length === 0) {
-      items = [labels.READING_TIME];
-    }
-    return items;
- 
```

**Comment by robole** [comment]
hi @riuson 

Yes, it was intentional to remove the method. While your assessment is correct about the behavior if someone unchecks all of the options in the `QuickPick`, I also found your approach counterintuitive. I was confused when I tested it, I did not see this method in the code originally and did not revisit it before testing it. It made me question if I actually unchecked all of the boxes when I did some manual testing.

Ideally, we would validate the selections that the user makes similar to a web form. We would like the same behaviour for the  `QuickPick` and the _Settings_, we would issue a warning and prohibit this state from being saved. The user would have to choose one option. However, there are limitations with the API that mean we can't validate like this. A compromise must be made.  I chose the simplest of the options and did exactly what the user requested. 

How likely is a user going to do this? It is very unlikely in my opinion. So is it worth more time?

I spent a few hours revising the code to add more test cases, I found and fixed a bug, and added 2 more settings. I did not anticipate spending this much time on this. This is not time I have to spare really, but I enjoy doing it occasionally.

The options for what can be done for the scenario when the user selects no stat options are the following:
1. The current behaviour is to show exactly what the user chooses. We set the label of the status bar item to an empty string when no stat options are selected. This means that the status bar item can no longer be clicked, but it can be restored by going to the _Settings_ and selecting a stat option. 
2. We could set the label of the status bar item to alternative string such  as "?" or "No option selected", so that it is still clickable.
3. We could do the same as what you did and force the selection of the "Reading Time" option in the background. I would show a toast information message to inform the user what was done (through `window.showInformationMessage`), otherwise they may not know what happened.
4. We could create a custom [QuickPick](https://code.visualstudio.com/api/references/vscode-api#QuickPick%3CT%3E) where you can perform validation in the `onDidAccept` event. You can show an error toast message when no options are selected. We can only accept the selection when at least one option is selected. For the _Settings_, it is still not possible to validate ,as far as I can tell. The `workspace.onDidChangeConfiguration` event returns a [`ConfigurationChangeEvent`](https://code.visualstudio.com/api/references/vscode-api#ConfigurationChangeEvent), which only has one method which returns a boolean to say whether a change has occurred or not. You cannot validate the selection with this info. So, in this case we have 2 different behaviours depending on how the user updates the stats options. You still need to do something like the previous options if you want to prohibit the status bar item label being an empty string.
5. Change the design. Maybe, consolidate the stat config properties into a single property that accepts parameters within the string. e.g. "${readingTime}${words}". You can specify a regex to validate this string in the `package.json`.

If you have an opinion on what course of action you prefer, you can let me know.  I don't think any of the options are particularly good. Option 2 is probably the simplest solution that covers the bases.

I will change the title of this issue to reflect the issue better. I will leave it open for now. I won't be taking any action on this for a while.

**Comment by robole** [comment]
v0.6.2 sets the label to "No stat selected" when no stat is selected
